apiVersion: v1
kind: Service
metadata:
  name: streamflix-v1-service
  labels:
    app: streamflix
    version: v1
spec:
  type: LoadBalancer
  selector:
    app: streamflix
    version: v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
