apiVersion: v1
kind: Service
metadata:
  name: streamflix-service
spec:
  type: LoadBalancer
  selector:
    app: streamflix
    version: v1   # BLUE is live
  ports:
    - port: 80
      targetPort: 5000
